// Tomorrowland Belgium 2026 — Weekend 2 (24-26 juillet)
// Source: festivaldust.com
// Day 1 = Vendredi 24 juillet | Day 2 = Samedi 25 juillet | Day 3 = Dimanche 26 juillet

const LINEUP = [
  // DAY 1 — VENDREDI 24 JUILLET
  { id: 1, name: "$HIRAK", stage: "Elixir", day: 1 },
  { id: 2, name: "5NAPBACK", stage: "The Library", day: 1 },
  { id: 3, name: "AARON HIBELL", stage: "Freedom by Bud", day: 1 },
  { id: 4, name: "AAT", stage: "Rise", day: 1 },
  { id: 5, name: "ALAN ALVAREZ & CRAZY SIR-G", stage: "House of Fortune by JBL", day: 1 },
  { id: 6, name: "ALAN WALKER", stage: "The Library", day: 1 },
  { id: 7, name: "ALESSO", stage: "Freedom by Bud", day: 1 },
  { id: 8, name: "ALLEYCVT", stage: "The Rose Garden", day: 1 },
  { id: 9, name: "ALOK", stage: "Mainstage", day: 1 },
  { id: 10, name: "AMBER BROOS B2B JULIET FOX", stage: "Freedom by Bud", day: 1 },
  { id: 11, name: "AVALON", stage: "Planaxis", day: 1 },
  { id: 12, name: "AZYR", stage: "Atmosphere", day: 1 },
  { id: 13, name: "B JONES", stage: "The Library", day: 1 },
  { id: 14, name: "BASSTRIPPER", stage: "The Rose Garden", day: 1 },
  { id: 15, name: "BAZZY", stage: "Cage", day: 1 },
  { id: 16, name: "BEAT CONTROLLERS", stage: "Planaxis", day: 1 },
  { id: 17, name: "BELTERS ONLY", stage: "Rise", day: 1 },
  { id: 18, name: "BIBI SECK B2B FAISAL", stage: "Core", day: 1 },
  { id: 19, name: "BLASTOYZ", stage: "Planaxis", day: 1 },
  { id: 20, name: "BLAZY", stage: "Planaxis", day: 1 },
  { id: 21, name: "BORGORE", stage: "The Rose Garden", day: 1 },
  { id: 22, name: "BOU", stage: "The Rose Garden", day: 1 },
  { id: 23, name: "BOY&GIRL", stage: "Atmosphere", day: 1 },
  { id: 24, name: "BROOKE BAILEY B2B TALIYAH AYANA", stage: "Elixir", day: 1 },
  { id: 25, name: "BULLET TOOTH", stage: "Core", day: 1 },
  { id: 26, name: "BYORN B2B SHLØMO", stage: "Atmosphere", day: 1 },
  { id: 27, name: "CALLUSH", stage: "Atmosphere", day: 1 },
  { id: 28, name: "CAPOON", stage: "Crystal Garden", day: 1 },
  { id: 29, name: "CHAM B2B UNEAK", stage: "Elixir", day: 1 },
  { id: 30, name: "DANY NEVILLE", stage: "Elixir", day: 1 },
  { id: 31, name: "DECO", stage: "Crystal Garden", day: 1 },
  { id: 32, name: "DJ FURAX", stage: "Cage", day: 1 },
  { id: 33, name: "DOMI RE", stage: "Planaxis", day: 1 },
  { id: 34, name: "DRS B2B SANDY WAREZ", stage: "Cage", day: 1 },
  { id: 35, name: "DYEN B2B MADDIX", stage: "Atmosphere", day: 1 },
  { id: 36, name: "ELECTRIC UNIVERSE", stage: "Planaxis", day: 1 },
  { id: 37, name: "ELY OAKS", stage: "Mainstage", day: 1 },
  { id: 38, name: "ESIN BOZ", stage: "Freedom by Bud", day: 1 },
  { id: 39, name: "FAIS LE BEAU B2B SIXSIXSIXTIES", stage: "Core", day: 1 },
  { id: 40, name: "FIRAGA", stage: "Planaxis", day: 1 },
  { id: 41, name: "FISHER", stage: "Freedom by Bud", day: 1 },
  { id: 42, name: "FLASH", stage: "Elixir", day: 1 },
  { id: 43, name: "GHENGAR", stage: "The Rose Garden", day: 1 },
  { id: 44, name: "GISSA", stage: "Rise", day: 1 },
  { id: 45, name: "HALŌ", stage: "The Library", day: 1 },
  { id: 46, name: "HARDWELL", stage: "Mainstage", day: 1 },
  { id: 47, name: "HOLY PRIEST", stage: "Atmosphere", day: 1 },
  { id: 48, name: "HUGEL", stage: "Crystal Garden", day: 1 },
  { id: 49, name: "ILLENIUM", stage: "The Library", day: 1 },
  { id: 50, name: "IMHAPPY", stage: "Cage", day: 1 },
  { id: 51, name: "INDIRA PAGANOTTO", stage: "Mainstage", day: 1 },
  { id: 52, name: "IRIS ROOTH", stage: "Elixir", day: 1 },
  { id: 53, name: "IRWAN", stage: "Elixir", day: 1 },
  { id: 54, name: "JAMES HYPE", stage: "Freedom by Bud", day: 1 },
  { id: 55, name: "JESSICA AUDIFFRED", stage: "The Rose Garden", day: 1 },
  { id: 56, name: "JO COX", stage: "Moose Bar", day: 1 },
  { id: 57, name: "JOA", stage: "Freedom by Bud", day: 1 },
  { id: 58, name: "JOEZI", stage: "Crystal Garden", day: 1 },
  { id: 59, name: "JOHN NOSEDA", stage: "Melodia by Corona", day: 1 },
  { id: 60, name: "JOULIE", stage: "Melodia by Corona", day: 1 },
  { id: 61, name: "KAMMA", stage: "Core", day: 1 },
  { id: 62, name: "KASKADE", stage: "The Library", day: 1 },
  { id: 63, name: "KITTY AMOR B2B CUROL", stage: "Crystal Garden", day: 1 },
  { id: 64, name: "KÖLSCH", stage: "Mainstage", day: 1 },
  { id: 65, name: "LEKKERFACES", stage: "Cage", day: 1 },
  { id: 66, name: "LOCUS", stage: "Planaxis", day: 1 },
  { id: 67, name: "LOU8", stage: "The Rave Cave", day: 1 },
  { id: 68, name: "MAHMUT ORHAN", stage: "Crystal Garden", day: 1 },
  { id: 69, name: "MAIREE", stage: "The Rave Cave", day: 1 },
  { id: 70, name: "MALIVE", stage: "Crystal Garden", day: 1 },
  { id: 71, name: "MALL GRAB", stage: "Core", day: 1 },
  { id: 72, name: "MANDY", stage: "The Library", day: 1 },
  { id: 73, name: "MARTIN TREVY", stage: "House of Fortune by JBL", day: 1 },
  { id: 74, name: "MC STRETCH", stage: "Mainstage", day: 1 },
  { id: 75, name: "MEAGHAN", stage: "The Library", day: 1 },
  { id: 76, name: "MEROW", stage: "The Library", day: 1 },
  { id: 77, name: "MHA IRI", stage: "Atmosphere", day: 1 },
  { id: 78, name: "MIRO", stage: "Elixir", day: 1 },
  { id: 79, name: "MISS MONIQUE", stage: "Mainstage", day: 1 },
  { id: 80, name: "MR. BELT & WEZOL", stage: "Rise", day: 1 },
  { id: 81, name: "MR. JOY", stage: "The Rave Cave", day: 1 },
  { id: 82, name: "NATTE VISSTICK", stage: "Cage", day: 1 },
  { id: 83, name: "NEMS", stage: "Elixir", day: 1 },
  { id: 84, name: "NICKY ROMERO", stage: "Mainstage", day: 1 },
  { id: 85, name: "NOME.", stage: "The Library", day: 1 },
  { id: 86, name: "OGAZÓN", stage: "Core", day: 1 },
  { id: 87, name: "OMDAT HET KAN & AVERAGE ROB", stage: "The Library", day: 1 },
  { id: 88, name: "ONLYNUMBERS", stage: "Atmosphere", day: 1 },
  { id: 89, name: "OSCAR AND THE WOLF", stage: "Core", day: 1 },
  { id: 90, name: "PARTYRAISER B2B BULLETPROOF", stage: "Cage", day: 1 },
  { id: 91, name: "PHAXE", stage: "Planaxis", day: 1 },
  { id: 92, name: "PLANET GROOVE DJ'S", stage: "Melodia by Corona", day: 1 },
  { id: 93, name: "PROSIT", stage: "Moose Bar", day: 1 },
  { id: 94, name: "RIOT TEN", stage: "The Rose Garden", day: 1 },
  { id: 95, name: "ROSH", stage: "Elixir", day: 1 },
  { id: 96, name: "RUZE B2B RANGER TRUCCO", stage: "Rise", day: 1 },
  { id: 97, name: "SAAR KUUS", stage: "Rise", day: 1 },
  { id: 98, name: "SHIMZA", stage: "Crystal Garden", day: 1 },
  { id: 99, name: "SKELETOR YOGI", stage: "Atmosphere", day: 1 },
  { id: 100, name: "SOMNIA", stage: "Planaxis", day: 1 },
  { id: 101, name: "SPIES", stage: "Melodia by Corona", day: 1 },
  { id: 102, name: "STEVE ANGELLO", stage: "Mainstage", day: 1 },
  { id: 103, name: "SULLIVAN KING", stage: "The Rose Garden", day: 1 },
  { id: 104, name: "TERRORCLOWN", stage: "Cage", day: 1 },
  { id: 105, name: "THE BOBMEISTER", stage: "Moose Bar", day: 1 },
  { id: 106, name: "JEROEN DELODDER", stage: "Melodia by Corona", day: 1 },

  // DAY 2 — SAMEDI 25 JUILLET
  { id: 201, name: "2HOT2PLAY", stage: "Atmosphere", day: 2 },
  { id: 202, name: "AGENTS OF TIME", stage: "Mainstage", day: 2 },
  { id: 203, name: "ALICIA HAHN", stage: "Planaxis", day: 2 },
  { id: 204, name: "ANGEMI", stage: "Mainstage", day: 2 },
  { id: 205, name: "ANNABEL STOP IT", stage: "Elixir", day: 2 },
  { id: 206, name: "ARGY", stage: "Freedom by Bud", day: 2 },
  { id: 207, name: "ARMIN VAN BUUREN", stage: "Mainstage", day: 2 },
  { id: 208, name: "BINGO PLAYERS WITH ICEMAN", stage: "Rise", day: 2 },
  { id: 209, name: "CALVIN HARRIS", stage: "Mainstage", day: 2 },
  { id: 210, name: "CARLY WILFORD", stage: "House of Fortune by JBL", day: 2 },
  { id: 211, name: "CHERRY MOON LEGENDS (& FRIENDS)", stage: "The Rose Garden", day: 2 },
  { id: 212, name: "CHOCOLATE PUMA", stage: "Rise", day: 2 },
  { id: 213, name: "CHRIS LORENZO", stage: "The Library", day: 2 },
  { id: 214, name: "COLYN B2B SAINTE VIE", stage: "Planaxis", day: 2 },
  { id: 215, name: "DADA LIFE", stage: "Rise", day: 2 },
  { id: 216, name: "DANNIC B2B DYRO", stage: "Rise", day: 2 },
  { id: 217, name: "DANNY CORTEN", stage: "The Rose Garden", day: 2 },
  { id: 218, name: "DIMITRI COOMAN", stage: "The Rose Garden", day: 2 },
  { id: 219, name: "DIMITRI VEGAS & LIKE MIKE", stage: "Mainstage", day: 2 },
  { id: 220, name: "DINO LENNY", stage: "Core", day: 2 },
  { id: 221, name: "DJ ART", stage: "Elixir", day: 2 },
  { id: 222, name: "DJ GHOST", stage: "The Rose Garden", day: 2 },
  { id: 223, name: "DYZEN", stage: "Planaxis", day: 2 },
  { id: 224, name: "EIMCO", stage: "Elixir", day: 2 },
  { id: 225, name: "EMILIA DE LA PAZ", stage: "Melodia by Corona", day: 2 },
  { id: 226, name: "EMILIJA B2B FENRICK", stage: "Atmosphere", day: 2 },
  { id: 227, name: "FLOWCHIEF", stage: "The Rave Cave", day: 2 },
  { id: 228, name: "FRANKY KLOECK", stage: "The Rose Garden", day: 2 },
  { id: 229, name: "GEHEIMZINNIG SOUNDSYSTEM", stage: "Melodia by Corona", day: 2 },
  { id: 230, name: "GORGON CITY", stage: "The Library", day: 2 },
  { id: 231, name: "GREGOR SALTO", stage: "Rise", day: 2 },
  { id: 232, name: "GUZ", stage: "Crystal Garden", day: 2 },
  { id: 233, name: "HAAI B2B THE BLESSED MADONNA", stage: "Core", day: 2 },
  { id: 234, name: "HENRI PFR", stage: "The Library", day: 2 },
  { id: 235, name: "I HATE MODELS", stage: "Atmosphere", day: 2 },
  { id: 236, name: "IOSIO", stage: "Cage", day: 2 },
  { id: 237, name: "JAMIE DILL", stage: "The Rose Garden", day: 2 },
  { id: 238, name: "JOHN SUMMIT", stage: "Crystal Garden", day: 2 },
  { id: 239, name: "JORIS VOORN B2B KONSTANTIN SIBOLD", stage: "Planaxis", day: 2 },
  { id: 240, name: "JORN PRICEZ", stage: "The Rave Cave", day: 2 },
  { id: 241, name: "JUSTIN WILKES", stage: "The Rave Cave", day: 2 },
  { id: 242, name: "KNEIZ", stage: "Atmosphere", day: 2 },
  { id: 243, name: "KNOX KIND", stage: "Elixir", day: 2 },
  { id: 244, name: "KURT VERHEYEN", stage: "Moose Bar", day: 2 },
  { id: 245, name: "LARRY MASMERO", stage: "Melodia by Corona", day: 2 },
  { id: 246, name: "LNY TNZ: JUMP NEVER DIES (TAKE-OVER)", stage: "Rise", day: 2 },
  { id: 247, name: "MACON", stage: "Cage", day: 2 },
  { id: 248, name: "MAITE DEDECKER", stage: "The Rose Garden", day: 2 },
  { id: 249, name: "MASSANO", stage: "Freedom by Bud", day: 2 },
  { id: 250, name: "MAX STYLER", stage: "Crystal Garden", day: 2 },
  { id: 251, name: "ME N Ü", stage: "The Library", day: 2 },
  { id: 252, name: "MERO B2B DAIRE", stage: "Cage", day: 2 },
  { id: 253, name: "MESTO", stage: "The Library", day: 2 },
  { id: 254, name: "MIKE WILLIAMS", stage: "Mainstage", day: 2 },
  { id: 255, name: "MOBIUS ONE", stage: "Moose Bar", day: 2 },
  { id: 256, name: "MONDELLO", stage: "Cage", day: 2 },
  { id: 257, name: "MOORIS", stage: "Melodia by Corona", day: 2 },
  { id: 258, name: "MORTEN", stage: "Mainstage", day: 2 },
  { id: 259, name: "MOSIMANN", stage: "House of Fortune by JBL", day: 2 },
  { id: 260, name: "MOSIMANN B2B ELFIGO", stage: "Freedom by Bud", day: 2 },
  { id: 261, name: "NA:TUS", stage: "Planaxis", day: 2 },
  { id: 262, name: "NAOMI CAZIER", stage: "Crystal Garden", day: 2 },
  { id: 263, name: "NETSKY", stage: "The Library", day: 2 },
  { id: 264, name: "NINA BLACK", stage: "Elixir", day: 2 },
  { id: 265, name: "NIOTECH", stage: "Cage", day: 2 },
  { id: 266, name: "NOISE MAFIA", stage: "Atmosphere", day: 2 },
  { id: 267, name: "NOVAH", stage: "Atmosphere", day: 2 },
  { id: 268, name: "ODYMEL", stage: "Mainstage", day: 2 },
  { id: 269, name: "ODSSEY", stage: "Rise", day: 2 },
  { id: 270, name: "PEGASSI", stage: "Atmosphere", day: 2 },
  { id: 271, name: "QUINCY", stage: "The Rose Garden", day: 2 },
  { id: 272, name: "RADIO CARGO", stage: "The Library", day: 2 },
  { id: 273, name: "ROMA", stage: "The Rave Cave", day: 2 },
  { id: 274, name: "RUBY XX", stage: "Elixir", day: 2 },
  { id: 275, name: "RUNE EVENS", stage: "Cage", day: 2 },
  { id: 276, name: "SAM GIRLING", stage: "Melodia by Corona", day: 2 },
  { id: 277, name: "SANDER VAN DOORN", stage: "Rise", day: 2 },
  { id: 278, name: "SANDERSVILLE", stage: "Elixir", day: 2 },
  { id: 279, name: "SÉA", stage: "Melodia by Corona", day: 2 },
  { id: 280, name: "SEBASTIAN INGROSSO", stage: "Freedom by Bud", day: 2 },
  { id: 281, name: "SHOARMA SOUNDSYSTEM", stage: "Elixir", day: 2 },
  { id: 282, name: "SICK INDIVIDUALS", stage: "Planaxis", day: 2 },
  { id: 283, name: "SONNY FODERA", stage: "The Library", day: 2 },
  { id: 284, name: "SOULASTICO B2B TOHMA", stage: "Melodia by Corona", day: 2 },
  { id: 285, name: "STANNE", stage: "Cage", day: 2 },
  { id: 286, name: "SUB ZERO PROJECT", stage: "Mainstage", day: 2 },
  { id: 287, name: "SWANKY TUNES", stage: "Rise", day: 2 },
  { id: 288, name: "SYMPHONY OF UNITY", stage: "Freedom by Bud", day: 2 },

  // DAY 3 — DIMANCHE 26 JUILLET
  { id: 301, name: "ADRIÁN MILLS", stage: "Atmosphere", day: 3 },
  { id: 302, name: "AFROJACK B2B R3HAB", stage: "Mainstage", day: 3 },
  { id: 303, name: "ALEX KENNON", stage: "Melodia by Corona", day: 3 },
  { id: 304, name: "ALYCIA BEZGO B2B BIIANCO", stage: "Atmosphere", day: 3 },
  { id: 305, name: "AMALIE", stage: "Cage", day: 3 },
  { id: 306, name: "AMELIE LENS PRESENTS AURA", stage: "Freedom by Bud", day: 3 },
  { id: 307, name: "AMOTIK", stage: "Cage", day: 3 },
  { id: 308, name: "ANDROMEDIK", stage: "Freedom by Bud", day: 3 },
  { id: 309, name: "ARTBAT", stage: "Freedom by Bud", day: 3 },
  { id: 310, name: "AXEL HAUBE", stage: "Freedom by Bud", day: 3 },
  { id: 311, name: "BASSBRAIN", stage: "The Rose Garden", day: 3 },
  { id: 312, name: "BASSJACKERS", stage: "The Library", day: 3 },
  { id: 313, name: "BELLA CLAXTON B2B PAIGE TOMLINSON", stage: "Rise", day: 3 },
  { id: 314, name: "BHASKAR", stage: "Crystal Garden", day: 3 },
  { id: 315, name: "BLASHA & ALLATT", stage: "Cage", day: 3 },
  { id: 316, name: "BOBBI ANTONNI", stage: "Melodia by Corona", day: 3 },
  { id: 317, name: "BRENNAN HEART", stage: "The Library", day: 3 },
  { id: 318, name: "BRIAN", stage: "Moose Bar", day: 3 },
  { id: 319, name: "BRINA KNAUSS", stage: "Crystal Garden", day: 3 },
  { id: 320, name: "CATALINA", stage: "Core", day: 3 },
  { id: 321, name: "CHASE & STATUS", stage: "Mainstage", day: 3 },
  { id: 322, name: "CHUCKIE", stage: "Planaxis", day: 3 },
  { id: 323, name: "COONE", stage: "The Rose Garden", day: 3 },
  { id: 324, name: "CRISTIANO DA SILVA", stage: "Melodia by Corona", day: 3 },
  { id: 325, name: "CYRIL", stage: "Mainstage", day: 3 },
  { id: 326, name: "D-CHARGED B2B SERZO", stage: "The Rose Garden", day: 3 },
  { id: 327, name: "D. GUAETTA B2B NEON", stage: "The Rave Cave", day: 3 },
  { id: 328, name: "DA TWEEKAZ", stage: "The Rose Garden", day: 3 },
  { id: 329, name: "DARREN STYLES", stage: "The Library", day: 3 },
  { id: 330, name: "DELAFINO & LUNA FINO", stage: "Melodia by Corona", day: 3 },
  { id: 331, name: "DEORRO", stage: "Planaxis", day: 3 },
  { id: 332, name: "DIEGO MIRANDA B2B JERRY DAVILA", stage: "The Library", day: 3 },
  { id: 333, name: "DIMITRI VEGAS", stage: "The Library", day: 3 },
  { id: 334, name: "DINO", stage: "Elixir", day: 3 },
  { id: 335, name: "ELI ROJAS", stage: "Melodia by Corona", day: 3 },
  { id: 336, name: "EME", stage: "The Rave Cave", day: 3 },
  { id: 337, name: "FIDELES", stage: "Freedom by Bud", day: 3 },
  { id: 338, name: "FRANC FALA B2B BENJA", stage: "Crystal Garden", day: 3 },
  { id: 339, name: "FREDDY K", stage: "Cage", day: 3 },
  { id: 340, name: "HARD DRIVER", stage: "The Rose Garden", day: 3 },
  { id: 341, name: "HELENA LAUWAERT", stage: "Core", day: 3 },
  { id: 342, name: "HU", stage: "Rise", day: 3 },
  { id: 343, name: "HYALYTE", stage: "The Rave Cave", day: 3 },
  { id: 344, name: "HYPATON", stage: "The Library", day: 3 },
  { id: 345, name: "JAËL OST & MAGIK", stage: "Elixir", day: 3 },
  { id: 346, name: "JAN V", stage: "Moose Bar", day: 3 },
  { id: 347, name: "KAV VERHOUZER & DE HOFNAR PRESENTS: EURODANCE", stage: "Elixir", day: 3 },
  { id: 348, name: "KARAKALS", stage: "Elixir", day: 3 },
  { id: 349, name: "KELLAR", stage: "Core", day: 3 },
  { id: 350, name: "KEVIN DE VRIES B2B MEDUZA", stage: "Crystal Garden", day: 3 },
  { id: 351, name: "KOBOSIL", stage: "Atmosphere", day: 3 },
  { id: 352, name: "KOROLOVA", stage: "Freedom by Bud", day: 3 },
  { id: 353, name: "KRISS REEVE", stage: "The Rave Cave", day: 3 },
  { id: 354, name: "KYLE STARKEY", stage: "Rise", day: 3 },
  { id: 355, name: "LAIDBACK LUKE", stage: "Planaxis", day: 3 },
  { id: 356, name: "LAMMER", stage: "Core", day: 3 },
  { id: 357, name: "LENNERT WOLFS", stage: "Elixir", day: 3 },
  { id: 358, name: "LIKE MIKE", stage: "Crystal Garden", day: 3 },
  { id: 359, name: "LISA KORVER", stage: "Rise", day: 3 },
  { id: 360, name: "LOST FREQUENCIES", stage: "Mainstage", day: 3 },
  { id: 361, name: "LOST IDENTITY", stage: "The Rose Garden", day: 3 },
  { id: 362, name: "LUCAS & STEVE", stage: "Mainstage", day: 3 },
  { id: 363, name: "MALUGI", stage: "Core", day: 3 },
  { id: 364, name: "MARK WITH A K & MC CHUCKY", stage: "The Rose Garden", day: 3 },
  { id: 365, name: "MARTIN GARRIX", stage: "Mainstage", day: 3 },
  { id: 366, name: "MATTN", stage: "The Library", day: 3 },
  { id: 367, name: "MENDOSA", stage: "Rise", day: 3 },
  { id: 368, name: "MICHAEL AMANI", stage: "Elixir", day: 3 },
  { id: 369, name: "MICHAEL AMANI & FRIENDS", stage: "Elixir", day: 3 },
  { id: 370, name: "MIND AGAINST", stage: "Crystal Garden", day: 3 },
  { id: 371, name: "MIRAGE", stage: "Atmosphere", day: 3 },
  { id: 372, name: "MR E.", stage: "Moose Bar", day: 3 },
  { id: 373, name: "MR. REWIND", stage: "The Rave Cave", day: 3 },
  { id: 374, name: "MUZE", stage: "The Rave Cave", day: 3 },
  { id: 375, name: "NERVO", stage: "The Library", day: 3 },
  { id: 376, name: "NETTY HUGO", stage: "Cage", day: 3 },
  { id: 377, name: "NEWTONE", stage: "Rise", day: 3 },
  { id: 378, name: "NICO MORENO", stage: "The Library", day: 3 },
  { id: 379, name: "NIKOLINA", stage: "Atmosphere", day: 3 },
  { id: 380, name: "ODD MOB", stage: "Mainstage", day: 3 },
  { id: 381, name: "OKAYVAL", stage: "Planaxis", day: 3 },
  { id: 382, name: "ORIOL CALVO", stage: "Melodia by Corona", day: 3 },
  { id: 383, name: "PORTEX", stage: "Atmosphere", day: 3 },
  { id: 384, name: "PUSH ONLY", stage: "Freedom by Bud", day: 3 },
  { id: 385, name: "QUELZA", stage: "Cage", day: 3 },
  { id: 386, name: "QUINTINO", stage: "Planaxis", day: 3 },
  { id: 387, name: "RAYCO SANTOS", stage: "Melodia by Corona", day: 3 },
  { id: 388, name: "REEZE", stage: "Elixir", day: 3 },
  { id: 389, name: "REZZ", stage: "Freedom by Bud", day: 3 },
  { id: 390, name: "RIANA HOLLEY", stage: "Atmosphere", day: 3 },
  { id: 391, name: "SAIDAH", stage: "Core", day: 3 },
  { id: 392, name: "SARA LANDRY", stage: "Mainstage", day: 3 },
  { id: 393, name: "SOUND RUSH", stage: "The Rose Garden", day: 3 },
  { id: 394, name: "STEVE AOKI", stage: "Mainstage", day: 3 },
  { id: 395, name: "SUPERHEROES", stage: "Planaxis", day: 3 },
  { id: 396, name: "THE CRIMINAL SOUNDS", stage: "House of Fortune by JBL", day: 3 },
  { id: 397, name: "ALEX KENNON", stage: "Melodia by Corona", day: 3 },
  { id: 398, name: "DOMINICO", stage: "Melodia by Corona", day: 3 },
  { id: 399, name: "DJ LEX", stage: "House of Fortune by JBL", day: 3 },
];

// Remove duplicates by id
const seen = new Set();
const LINEUP_CLEAN = LINEUP.filter(a => {
  const key = a.name + '-' + a.day;
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});

const STAGES = [...new Set(LINEUP_CLEAN.map(a => a.stage))].sort();
const DAY_LABELS = { 1: "Vendredi 24/07", 2: "Samedi 25/07", 3: "Dimanche 26/07" };

// Stage color mapping
const STAGE_COLORS = {
  "Mainstage": "#FF6B35",
  "Freedom by Bud": "#9B59B6",
  "The Library": "#3498DB",
  "Crystal Garden": "#2ECC71",
  "Core": "#E74C3C",
  "Planaxis": "#F39C12",
  "Atmosphere": "#1ABC9C",
  "The Rose Garden": "#E91E8C",
  "Cage": "#795548",
  "Elixir": "#00BCD4",
  "Rise": "#FF9800",
  "The Rave Cave": "#607D8B",
  "Melodia by Corona": "#8BC34A",
  "House of Fortune by JBL": "#FF5722",
  "Moose Bar": "#9E9E9E",
};
